export const sizeInfo = {
  kurti: ["length", "chest", "waist", "hip", "sleeves", "shoulder", "neck"],
  pant: ["length", "waist", "hip", "thigh"],
  gown: [
    "length",
    "chest",
    "waist",
    "hip",
    "sleeves",
    "shoulder",
    "neck",
    "yog",
  ],
  lehenga: ["length", "waist", "hip"],
  dress: [
    "length",
    "chest",
    "waist",
    "hip",
    "sleeves",
    "shoulder",
    "neck",
    "yog",
  ],
  plazo: ["length", "waist", "hip", "thigh"],
  sharara: ["length", "waist", "hip", "thigh"],
  garara: ["length", "waist", "hip", "thigh"],
  skirt: ["length", "waist", "hip"],
  blouse: ["length", "chest", "waist", "front_neck", "back_neck", "shoulder"],
};
