export const CART_SET = "CART_SET";
export const CART_CLEAR = "CART_CLEAR";

export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

export const CART_GET_REQUEST = "CART_GET_REQUEST";
export const CART_GET_SUCCESS = "CART_GET_SUCCESS";
export const CART_GET_FAIL = "CART_GET_FAIL";

export const CART_ADD_REQUEST = "CART_ADD_REQUEST";
export const CART_ADD_SUCCESS = "CART_ADD_SUCCESS";
export const CART_ADD_FAIL = "CART_ADD_FAIL";
export const CART_ADD_RESET = "CART_ADD_RESET";

export const CART_REMOVE_REQUEST = "CART_REMOVE_REQUEST";
export const CART_REMOVE_SUCCESS = "CART_REMOVE_SUCCESS";
export const CART_REMOVE_FAIL = "CART_REMOVE_FAIL";
export const CART_REMOVE_RESET = "CART_REMOVE_RESET";

export const BUY_NOW_PRODUCT_ADD = "BUY_NOW_PRODUCT_ADD";
export const BUY_NOW_PRODUCT_RESET = "BUY_NOW_PRODUCT_RESET";

export const CART_QTY_UPDATE_REQUEST = "CART_QTY_UPDATE_REQUEST";
export const CART_QTY_UPDATE_SUCCESS = "CART_QTY_UPDATE_SUCCESS";
export const CART_QTY_UPDATE_FAIL = "CART_QTY_UPDATE_FAIL";

export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SHIPPING_ADDRESS_FAIL = "CART_SHIPPING_ADDRESS_FAIL";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";

export const FAV_SET = "FAV_SET";
export const FAV_CLEAR = "FAV_CLEAR";

export const FAV_ADD_ITEM = "FAV_ADD_ITEM";
export const FAV_REMOVE_ITEM = "FAV_REMOVE_ITEM";

export const FAV_GET_REQUEST = "FAV_GET_REQUEST";
export const FAV_GET_SUCCESS = "FAV_GET_SUCCESS";
export const FAV_GET_FAIL = "FAV_GET_FAIL";

export const FAV_ADD_REQUEST = "FAV_ADD_REQUEST";
export const FAV_ADD_SUCCESS = "FAV_ADD_SUCCESS";
export const FAV_ADD_RESET = "FAV_ADD_RESET";
export const FAV_ADD_FAIL = "FAV_ADD_FAIL";

export const FAV_REMOVE_REQUEST = "FAV_REMOVE_REQUEST";
export const FAV_REMOVE_SUCCESS = "FAV_REMOVE_SUCCESS";
export const FAV_REMOVE_RESET = "FAV_REMOVE_RESET";
export const FAV_REMOVE_FAIL = "FAV_REMOVE_FAIL";
